# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1551uTuuI6EBubl6so52pG2XH8KbJyoDf
"""

import streamlit as st
import google.generativeai as genai
import pandas as pd
import json
from datetime import datetime
import io
from docx import Document
from docx.shared import Pt

# --------------- App config ---------------
st.set_page_config(page_title="Document Generation Agent", page_icon="📝", layout="wide")

# Session state
if "history" not in st.session_state:
    st.session_state.history = []
if "uploaded_df" not in st.session_state:
    st.session_state.uploaded_df = None
if "uploaded_filename" not in st.session_state:
    st.session_state.uploaded_filename = None

# --------------- Helpers ---------------
def configure_gemini(api_key: str, model_name: str = "gemini-1.5-mini"):
    """Configure google.generativeai and return a model wrapper."""
    genai.configure(api_key=api_key)
    return genai.GenerativeModel(model_name)

def read_uploaded_file(uploaded_file):
    try:
        name = uploaded_file.name.lower()
        if name.endswith(".csv"):
            df = pd.read_csv(uploaded_file)
        elif name.endswith((".xls", ".xlsx")):
            df = pd.read_excel(uploaded_file, engine="openpyxl")
        else:
            return None, "Unsupported file type. Use CSV or XLSX."
        return df, None
    except Exception as e:
        return None, str(e)

def df_to_markdown_table(df: pd.DataFrame) -> str:
    if df is None or df.empty:
        return "(no data)"
    return df.to_markdown(index=False)

def markdown_to_docx(markdown_text: str) -> Document:
    """Lightweight markdown -> docx converter for headings, bullets and paragraphs."""
    doc = Document()
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Calibri"
    font.size = Pt(11)

    for line in markdown_text.splitlines():
        l = line.strip()
        if not l:
            doc.add_paragraph()
            continue
        if l.startswith("# "):
            p = doc.add_paragraph()
            run = p.add_run(l.replace("# ", ""))
            run.bold = True
            run.font.size = Pt(16)
        elif l.startswith("## "):
            p = doc.add_paragraph()
            run = p.add_run(l.replace("## ", ""))
            run.bold = True
            run.font.size = Pt(14)
        elif l.startswith("### "):
            p = doc.add_paragraph()
            run = p.add_run(l.replace("### ", ""))
            run.bold = True
            run.font.size = Pt(12)
        elif l.startswith("- "):
            doc.add_paragraph(l.replace("- ", ""), style="List Bullet")
        else:
            doc.add_paragraph(l)
    return doc

# --------------- Prompt templates ---------------
TEMPLATES = {
    "report": """You are a professional report writer. Given the context and data below, produce a clear, structured report in markdown with sections:
# Executive Summary
## Key Metrics
## Analysis
## Recommendations
## Next Steps

Context:
{context}

Data (as table):
{data_table}
""",
    "proposal": """You are a persuasive business proposal writer. Using the context and data below, produce a professional proposal in markdown including:
# Executive Summary
## Objectives
## Scope of Work
## Deliverables
## Timeline
## Pricing
## Terms

Context:
{context}

Data (as table):
{data_table}
""",
    "contract": """You are a legal-aware assistant. Draft a plain-language contract in markdown using details below. Include:
# Parties
## Effective Date
## Scope
## Deliverables
## Payment Terms
## Confidentiality
## Termination
## Signatures

Details:
{context}

Data (as table):
{data_table}
""",
    "sop": """You are a process documentation expert. Create a Standard Operating Procedure (SOP) in markdown including:
# Purpose
## Scope
## Responsibilities
## Procedure (step-by-step)
## Quality Checks
## Revision History

Context:
{context}

Data (as table):
{data_table}
""",
    "project_plan": """You are a project manager assistant. Produce a project plan in markdown with:
# Project Overview
## Objectives
## Milestones
## Tasks (owner, duration)
## Timeline
## Risks
## Communication Plan

Context:
{context}

Data (as table):
{data_table}
"""
}

# --------------- Sidebar ---------------
with st.sidebar:
    st.title("⚙️ Configuration")
    api_key = st.text_input("Google Gemini API Key", type="password")
    model_name = st.selectbox("Model", ["gemini-1.5-mini", "gemini-1.5", "gemini-1.5-pro"])
    st.markdown("---")
    st.caption("Optional: upload CSV/XLSX to include structured data in generated documents.")
    uploaded = st.file_uploader("Upload data (CSV/XLSX)", type=["csv", "xlsx", "xls"])
    if uploaded is not None:
        df, err = read_uploaded_file(uploaded)
        if err:
            st.error(err)
        else:
            st.session_state.uploaded_df = df
            st.session_state.uploaded_filename = uploaded.name
            st.success(f"Loaded {uploaded.name} ({len(df)} rows)")

# --------------- Main UI ---------------
st.title("📝 Document Generation Agent")
st.write("Auto-create Reports, Proposals, Contracts, SOPs, and Project Plans using Google Gemini.")

col1, col2 = st.columns([3, 1])
with col1:
    doc_type = st.selectbox("Document Type", ["report", "proposal", "contract", "sop", "project_plan"], format_func=lambda x: x.replace("_", " ").title())
    context = st.text_area("Context / Instructions", height=220, placeholder="Describe goals, audience, tone, constraints, and any specifics.")
    tone = st.selectbox("Tone", ["Professional", "Formal", "Concise", "Persuasive", "Casual"])
    length = st.selectbox("Desired length", ["Short (1-2 pages)", "Medium (3-5 pages)", "Long (6+ pages)"], index=1)

with col2:
    st.markdown("**Preview / Inputs**")
    if st.session_state.uploaded_df is not None:
        st.markdown(f"**Uploaded:** {st.session_state.uploaded_filename}")
        st.dataframe(st.session_state.uploaded_df.head(5))
    else:
        st.markdown("No data uploaded.")

st.divider()
generate = st.button("Generate Document")

if generate:
    if not api_key:
        st.error("Please enter your Google Gemini API Key in the sidebar.")
    else:
        try:
            model = configure_gemini(api_key, model_name)
            data_table = df_to_markdown_table(st.session_state.uploaded_df)
            template = TEMPLATES.get(doc_type)
            prompt = template.format(context=context or "(no context provided)", data_table=data_table)
            prompt += f"\n\nTone: {tone}. Desired length: {length}. Respond in markdown and include clear headings."

            with st.spinner("Generating document..."):
                resp = model.generate_content(prompt)
                output = resp.text.strip()

            # store history
            st.session_state.history.insert(0, {"type": doc_type, "time": datetime.now().isoformat(), "prompt": prompt, "output": output})

            st.subheader("Preview")
            st.markdown(output)

            # Download: markdown
            md_bytes = output.encode("utf-8")
            st.download_button("Download Markdown (.md)", md_bytes, file_name=f"{doc_type}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md", mime="text/markdown")

            # Download: docx
            doc = markdown_to_docx(output)
            buf = io.BytesIO()
            doc.save(buf)
            buf.seek(0)
            st.download_button("Download Word (.docx)", buf, file_name=f"{doc_type}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx")

        except Exception as e:
            st.error(f"Error generating document: {e}")

st.divider()
st.subheader("History")
for i, h in enumerate(st.session_state.history[:10]):
    with st.expander(f"{i+1}. {h['type'].replace('_',' ').title()} — {h['time']}"):
        st.markdown("**Prompt used:**")
        st.code(h['prompt'][:1000] + ("..." if len(h['prompt']) > 1000 else ""), language="text")
        st.markdown("**Output preview:**")
        st.markdown(h['output'][:2000] + ("..." if len(h['output']) > 2000 else ""))

st.caption("Built with Streamlit + Google Gemini. Always review generated legal documents before using.")